#
# Copyright (C) 2021-2022 The LineageOS Project
#
# SPDX-License-Identifier: Apache-2.0
#
LOCAL_PATH := $(call my-dir)

ifeq ($(TARGET_DEVICE),waffle)

include $(CLEAR_VARS)

PREBUILT_KERNEL_MODULES_SYSTEM_DLKM := $(TARGET_OUT_SYSTEM_DLKM)/lib/modules
$(PREBUILT_KERNEL_MODULES_SYSTEM_DLKM):
	@mkdir -p $(TARGET_OUT_SYSTEM_DLKM)/lib/modules
	@cp -r $(DEVICE_PATH)-prebuilt/modules/system_dlkm/6.1.* $(PREBUILT_KERNEL_MODULES_SYSTEM_DLKM)

PREBUILT_KERNEL_MODULES_SYSTEM_DLKM_FLATTEN := $(TARGET_OUT_SYSTEM_DLKM)/flatten/lib/modules
$(PREBUILT_KERNEL_MODULES_SYSTEM_DLKM_FLATTEN):
	@mkdir -p $(TARGET_OUT_SYSTEM_DLKM)/flatten/lib/modules
	@cp -r $(DEVICE_PATH)-prebuilt/modules/system_dlkm/flatten/* $(PREBUILT_KERNEL_MODULES_SYSTEM_DLKM_FLATTEN)

ALL_DEFAULT_INSTALLED_MODULES += $(PREBUILT_KERNEL_MODULES_SYSTEM_DLKM) $(PREBUILT_KERNEL_MODULES_SYSTEM_DLKM_FLATTEN)

endif
